title: Actor
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5215054
  brandStrength: 0.5232975
  lightness: 0.374552
  brandColors:
    - '#162042'
    - '#66645B'
    - '#FFFDF2'
    - '#8792BD'
    - '#C7625A'
  rhythmicContrast: 0.6474983
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Stuart Bowman
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6827957
layout_spectrum: 0.9014337
