name: Stuart Bowman
favicon: null
layout_spectrum: 0.9902801816351712
typography_spectrum: 0.8373041385784745
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7108836949337274
  lightness: 0.33301365561783314
  saturation: 0.3264461581129581
  rhythmicContrast: 0.6474982819054276
purpose: []
